apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns
spec:
  acme:
    email: email@domain.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-dns-private-key
    solvers:
      - dns01:
          cloudflare:
            email: email@domain.com
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
